# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='last name')),
                ('su_id', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, verbose_name='first name')),
                ('emergency_phone_number', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='doğum tarihi')),
                ('is_entry_fee_paid', models.BooleanField(default=False)),
                ('sailing_level', models.IntegerField(blank=True, null=True, verbose_name='yelken seviyesi')),
                ('club_management_position', models.CharField(blank=True, max_length=255, verbose_name='yönetim kurulu görevi')),
                ('sailing_team_position', models.CharField(blank=True, max_length=255, verbose_name='yarış takımı pozisyonu')),
                ('extra_information_about_member', models.TextField(blank=True)),
                ('is_visible_on_web', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='kayıt tarihi')),
                ('is_an_active_student', models.BooleanField(default=True)),
                ('is_school_staff', models.BooleanField(default=False)),
                ('is_gorbon_captain', models.BooleanField(default=False)),
                ('is_active_member', models.BooleanField(default=False)),
                ('susail_balance', models.IntegerField(blank=True)),
                ('last_visit', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
