# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='club_management_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='club management position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='record date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sailing_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='sailing level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sailing_team_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='sailing team position'),
        ),
    ]
